spring:
  liquibase.changeLog: classpath:/db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}
    username: ${POSTGRESQL_ADDON_USER}
    password: ${POSTGRESQL_ADDON_PASSWORD}

  cache:
    caffeine.spec: maximumSize=1000

bihan:
  base-redirect: https://www.breizhcamp.org/
  public-url: https://bzh.camp/